// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMcXPI1nsz4YHVZDux3Y29rzFYWSN6Mr0',
    appId: '1:172099016246:web:a3e47d765201c473da6a97',
    messagingSenderId: '172099016246',
    projectId: 'login-registration-f756d',
    authDomain: 'login-registration-f756d.firebaseapp.com',
    storageBucket: 'login-registration-f756d.firebasestorage.app',
    measurementId: 'G-3YEN8DXX8F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn-7ISRwbB9Bdphwiod-HMuB9hksMqn0o',
    appId: '1:172099016246:android:cce47a576aefef50da6a97',
    messagingSenderId: '172099016246',
    projectId: 'login-registration-f756d',
    storageBucket: 'login-registration-f756d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiAIIy1abWwbh1cqYEyX8RbRT4E62Uojo',
    appId: '1:172099016246:ios:b4428a2013c91a07da6a97',
    messagingSenderId: '172099016246',
    projectId: 'login-registration-f756d',
    storageBucket: 'login-registration-f756d.firebasestorage.app',
    iosBundleId: 'com.example.toDoWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiAIIy1abWwbh1cqYEyX8RbRT4E62Uojo',
    appId: '1:172099016246:ios:b4428a2013c91a07da6a97',
    messagingSenderId: '172099016246',
    projectId: 'login-registration-f756d',
    storageBucket: 'login-registration-f756d.firebasestorage.app',
    iosBundleId: 'com.example.toDoWithFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMcXPI1nsz4YHVZDux3Y29rzFYWSN6Mr0',
    appId: '1:172099016246:web:fadf8fb3a707de78da6a97',
    messagingSenderId: '172099016246',
    projectId: 'login-registration-f756d',
    authDomain: 'login-registration-f756d.firebaseapp.com',
    storageBucket: 'login-registration-f756d.firebasestorage.app',
    measurementId: 'G-DE6850CRGR',
  );
}
